### ISSUE TITLE
Patch to fix compilation issue related to zlib

### ISSUE THREAD

**Issue by Gallaecio** [Monthy/gr-lida#5]
http://git.chakraos.org/desktop.git/blob/0be796e73dc1429976ccd18113850fe6b76948ab:/gr-lida/zlib.patch

I had to apply that patch to successfully build gr-lida 0.11.0.

Just for the record, I found the solution at https://bugs.scribus.net/view.php?id=11850

**Comment by Monthy** [comment]
Thanks for the warning
Certainly it is no longer necessary to use the "use_zlib" as the zlib system is used
Updated and corrected osdab-zip

Sorry for my English
