### ISSUE TITLE
Refresh translation files

### ISSUE THREAD

**Issue by laenion** [Monthy/gr-lida#7]
Due to the class renames of the DOSBox / ScummVM / VDMSound wizards the translation files have to be regenerated - currently the wizards are always shown in Spanish ;-)

**Comment by Monthy** [comment]
Thanks for the warning,
During the week I will correct it.
Sorry for my English

Gracias por el aviso,
durante la semana lo corregiré.
Perdón por mi Ingles

**Comment by Monthy** [comment]
Updates
Actualizados
