### ISSUE TITLE
MobyGames plugin non-functional

### ISSUE THREAD

**Issue by laenion** [Monthy/gr-lida#8]
It seems MobyGames changed something so that the import script doesn't work as expected any more. The game list can be seen when confirming the redirection, but when trying to get the data of a game entry the error message
> Couldn't save the file: Host www.mobygames.comhttps not found.

is shown. The game data is not filled in.

**Comment by Monthy** [comment]
Sorry for my English
I will look at the changes that mobygames has made, at first glance it seems that it has changed from http to https.
It will take a little longer since it is not only update the import script, you also have to modify part of the code.

Thanks for the warning.

**Comment by Monthy** [comment]
Error fixed
Corrections are the main repository, SSL support cac4b4d6e0ea5ccda4f141ee9307a1b40b21c7c9 and Mobygame script update dff8dbb0b342446a9858436397416d77d20662c4

Error corregido
Las correcciones estan el repositorio principal, soporte SSL cac4b4d6e0ea5ccda4f141ee9307a1b40b21c7c9 y actualizacion del script mobygames dff8dbb0b342446a9858436397416d77d20662c4

**Comment by laenion** [comment]
Thanks a lot for the quick fix, everything is working as expected again!
