### ISSUE TITLE
Migration from old dbgrl_mnu_nav

### ISSUE THREAD

**Issue by laenion** [Monthy/gr-lida#9]
I recently updated to the current GR-lida version and get the following message during startup, when changing categories or going into the options since then:

```
SQL:
SELECT id, titulo, col_value, col_name, sql_query, archivo, img, orden, mostrar, expanded FROM dbgrl_mnu_nav ORDER BY orden ASC;

Error:
no such column: mostrar Unable to execute statement
```

It seems in https://github.com/Monthy/gr-lida/commit/6d8b988a171e9f76ab98f5925da33901ebb4b94d the `show` and `separator` columns were renamed, without doing any migration to the new names.

I fixed this for myself by dropping the `dbgrl_mnu_nav` table so that it gets regenerated, but it may be a good idea to migrate to the new names automatically...

**Comment by Monthy** [comment]
Hi laenion
Thanks for the warning, for future release it will be corrected 316061f28275a52ccf507fd940b0996b89b38d60
